services:
  database:
    extends:
      file: back/docker-compose.yml
      service: database

  php:
    extends:
      file: back/docker-compose.yml
      service: php
    volumes:
      - ./back/api:/srv/app

  pwa:
    extends:
      file: back/docker-compose.yml
      service: pwa
    volumes:
      - ./back/pwa:/srv/app

  caddy:
    extends:
      file: back/docker-compose.yml
      service: caddy

  node:
    extends:
      file: front/docker-compose.yml
      service: node



volumes:
  php_socket:
  caddy_data:
  caddy_config:
  ###> doctrine/doctrine-bundle ###
  db_data: