get_translations:
    path: '/translations/{language}'
    controller: App\Controller\TranslationController::getTranslations
    methods: ['GET']
get_medias:
    path: '/media/{filename}'
    controller: App\Controller\MediaController::serveMedia
    methods: ['GET']
