version: "3"

services:
  node:
    build: docker
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: /bin/sh -c "ls && cd app && npm install && npm run dev"
