name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push PHP Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./test
          file: ./test/Dockerfile
          push: true
          tags: ossama98/monapp_php:latest
          target: php
          cache-from: type=registry,ref=ossama98/monapp_php:latest
          cache-to: type=inline

  deploy_to_ec2:
    needs: build_and_push
    runs-on: instance-ec2
    steps:
      - name: Pull image from docker hub
        run: docker pull ossama98/monapp_php:latest
      - name: delete old container
        run: docker rm -f php
      - name: launch container php
        run: docker run --name php -d --network monapp_network ossama98/monapp_php
      - name: install dependencies
        run: docker exec php composer install
      - name: generate keypair
        run: docker exec php bin/console lexik:jwt:generate-keypair --overwrite --no-interaction
