on:
  pull_request:

jobs:
  ci-back:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: back

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
            workdir: back
            pull: true
            load: true
            files: |
              docker-compose.yml
              docker-compose.override.yml
            set: |
              *.cache-from=type=gha,scope=${{github.ref}}
              *.cache-from=type=gha,scope=refs/heads/main
              *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Start services
        run: docker compose up --wait --no-build

      - name: Check HTTP reachability
        run: curl -v -o /dev/null http://localhost

      - name: Check API reachability
        run: curl -vk -o /dev/null https://localhost

      - name: Check PWA reachability
        run: "curl -vk -o /dev/null -H 'Accept: text/html' https://localhost"

      - name: Run PHPUnit tests
        run: docker compose exec -T php bin/phpunit

      - name: Fail back
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID_FAIL }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN_FAIL }}
          color: "#ff0000"
          username: "Review Pelo Bot"
          avatar_url: "https://cdn.discordapp.com/attachments/1151784787057594428/1152126946789052436/image.png?ex=65321c55&is=651fa755&hm=88684c0f5b1c9aa5251f160c5a649525f98d047644cc3e81e64fa5f2b4681049&"
          message: ":loudspeaker: **Fail ci back in PR: ${{ github.event.pull_request.title }}** : ${{ github.event.pull_request.html_url }} @here"

  ci-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    needs: ci-back

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
          workdir: front
          pull: true
          load: true
          files: |
            docker-compose.yml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Start services
        working-directory: front
        run: docker compose up --wait --build

      - name: Install dependencies
        run: docker compose exec -T node pnpm install

      - name: Build
        run: docker compose exec -T node pnpm run build

      #- name: Install Playwright dependencies
      #  run: docker compose exec -T node pnpm dlx playwright install --with-deps

      #- name: Run Playwright tests
      #  run: docker compose exec -T node pnpm run test:e2e CI=1

      - name: Run Vitest tests
        run: docker compose exec -T node pnpm run test --no-watch

      - name: Fail front
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID_FAIL }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN_FAIL }}
          color: "#ff0000"
          username: "Review Pelo Bot"
          avatar_url: "https://cdn.discordapp.com/attachments/1151784787057594428/1152126946789052436/image.png?ex=65321c55&is=651fa755&hm=88684c0f5b1c9aa5251f160c5a649525f98d047644cc3e81e64fa5f2b4681049&"
          message: ":loudspeaker: **Fail ci front in PR: ${{ github.event.pull_request.title }}** : ${{ github.event.pull_request.html_url }} @here"

