on:
  pull_request:

jobs:
  ci-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'


  ci-front:
    needs: ci-back
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '21.x'
          cache: 'pnpm'
          cache-dependency-path: 'front/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Install Playwright dependencies
        run: pnpm dlx playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm run test:e2e

      - name: Run Vitest tests
        run: pnpm run test
