on:
  pull_request:

jobs:
  ci-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
            workdir: back
            pull: true
            load: true
            files: |
              docker-compose.yml
              docker-compose.override.yml
            set: |
              *.cache-from=type=gha,scope=${{github.ref}}
              *.cache-from=type=gha,scope=refs/heads/main
              *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Start services
        working-directory: ./back
        run: |
          docker-compose up --detach
          docker-compose logs -f back-php-1

      - name: Check HTTP reachability
        run: curl -v -o /dev/null http://localhost

      - name: Check API reachability
        run: curl -vk -o /dev/null https://localhost

      - name: Check PWA reachability
        run: "curl -vk -o /dev/null -H 'Accept: text/html' https://localhost"

      - name: Create test database
        run: docker-compose exec -T php bin/console -e test doctrine:database:create

      - name: Run migrations
        run: docker-compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction

      - name: Run PHPUnit tests
        run: docker-compose exec -T php bin/phpunit

      - name: Doctrine Schema Validator
        run: docker-compose exec -T php bin/console -e test doctrine:schema:validate

  ci-front:
    runs-on: ubuntu-latest
    needs: ci-back

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker images
        uses: docker/build-push-action@v3
        with:
          context: ./front
          tags: ${{ github.ref }}
          push: true

      - name: Start services
        working-directory: ./front
        run: docker-compose up --detach

      - name: Build
        run: docker-compose exec node pnpm run build

      - name: Install Playwright dependencies
        run: docker-compose exec node pnpm dlx playwright install --with-deps

      - name: Run Playwright tests
        run: docker-compose exec node pnpm run test:e2e

      - name: Run Vitest tests
        run: docker-compose exec node pnpm run test
