on:
  pull_request:
    types:
      - opened

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Send notification on Discord
          uses: appleboy/discord-action@master
          with:
            webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
            webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
            color: 15158332
            title: ${{ github.event.pull_request.title }}
            description: ${{ github.event.pull_request.body }}
